### ISSUE TITLE
Erreur de config Home assistant v2021.11.5

### ISSUE THREAD

**Issue by benoitsi1** [Aohzan/ipx800v5#1]
Bonjour,

J ai les erreurs suivantes en voulant rajouter l addon dans integration
"Le flux de configuration n'a pas pu être chargé"

En rajoutant dans config.yaml
le plugin ipx800v5
le check de syntaxe me donne l erreur suivante
Component error: ipx800v5 - cannot import name 'ENTITY_CATEGORY_SYSTEM' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

En vous remerciant d'avance

**Comment by Aohzan** [comment]
Bonjour,

Il faut la version 2021.12 minimum pour utiliser cette intégration (c'est spécifié dans le CHANGELOG), actuellement elle est en beta et doit être disponible le 11 décembre pour tous de mémoire

**Comment by benoitsi1** [comment]
Bonjour Matthieu,

Excellent et merci encore pour cette super integration et le super travail !
