### ISSUE TITLE
Extension X-POOL et X-DISPLAY

### ISSUE THREAD

**Issue by cocoffr** [Aohzan/ipx800v5#10]
bonjour
serait-il possible d'ajouter les 2 extensions X-POOL et X-DISPLAY ?
merci

**Comment by Aohzan** [comment]
Peux-tu me dire qu'est ce que tu voudrais avoir dans HA pour le X-Display (contrôle + information) ?
Pourrais-tu également faire une requête sur l'API `http://x.x.x.x/api/ebx/xdisplay` et me donner le retour

**Comment by cocoffr** [comment]
bonjour
le X-display permet l'affichage de valeur, et la commande de type on/off. donc afficher une valeur issue de HA serait pas mal (ex température), de même en commande changer l'état d'un bouleen serait pas mal pour pouvoir s'en servir dans HA pour faire une action.
suite à la requête que tu m'as demandé j'ai en retour {"Status":"Need AuthToken"}

**Comment by cocoffr** [comment]
bonjour
pour le X-pool ce que j'aimerais avoir sous Ha c'est l'ensemble des infos qui transitent entre lui et l'IPX : commande des relais, valeur PH, ORP, temps eau, temps air, entrée numérique + les notifs (sous, sur PH et ORP, et risque gel).

**Comment by Aohzan** [comment]
je regarde prochainement pour le xdisplay
pour le xpool il faudrait contacter GCE pour qu'ils mettent une API en place

**Comment by cocoffr** [comment]
rapide :)
la commande renvoie {"Status":"URI Not found"} donc a priori pas d'API pour le xpool :(

**Comment by cocoffr** [comment]
sinon j'ai trouvé une alternative en passant pas des analogiques virtuelles, j'arrive ainsi à récupère les valeurs de PH et ORP :)
super ton intégration !! (même si j'ai un peu galérer à comprendre, il a fallu que je désinstalle et réinstalle l'intégration car sinon ca ne voulait pas prendre en compte ce qu'il y avait dans le yaml) ...)
Nota : mqtt : je laisse tomber je ne comprend rien.

**Comment by Aohzan** [comment]
oui tu peux ajouter les io et ana en récupérant leur id et mettre tout ça dans la conf en yaml, ça va te débloquer en attendant en effet

**Comment by cocoffr** [comment]
en fait même pas le peine de passer par des variables virtuelles, si on appelle directement l'id du capteur de l'extension x-pool dans le yaml, ca remonte la bonne valeur.

**Comment by cocoffr** [comment]
bonsoir
avec la commande http://192.168.1.84/api/ebx/xpool?ApiKey=xxxxxxx ca ne répond rien mais avec
http://192.168.1.84/api/xdevice/xpool?ApiKey=xxx
ca répond : 
[{"_id":5242880,"Heater":"off","Filtration":"off","Light":"off","Aux":"off","Input Filtr":"off","Input Light":"off","Input Heater":"off","Input Aux":"off","Temp Exterior":0,"Temp Water":0,"Probe PH":7.9,"Probe ORP":-52.0,"Under Ph":"off","Upper Ph":"on","No Frozte":"off","Under Orp":"off","Upper Orp":"on"}]

**Comment by Aohzan** [comment]
Hello @cocoffr 
J'ai reçu un X-Display, je viens de l'intégrer dans 1.6.0, redis moi ce que tu en penses
