### ISSUE TITLE
mise a jour

### ISSUE THREAD

**Issue by Mickaelclercq** [Aohzan/ipx800v5#11]
bonjour le me permets de te contacter car ca fait plus de un an que j'utilise ton intégration et elle est fantastique, j'ai fait la mise a jour en version 1.51 au départ de la 1.46 j'ai une configuration en yaml le souci c'est qu'il ne prend pas en compte ma configuration yaml il reste sur une configuration de base, serais-tu m'aider me dire ou je fait une conneries???
![20230828_115903](https://github.com/Aohzan/ipx800v5/assets/104391247/7bbddebd-b739-4d3a-978b-2f0859321b53)
![20230828_115912](https://github.com/Aohzan/ipx800v5/assets/104391247/5a88a61a-4a19-499c-8baf-e326377bd926)
![20230828_115918](https://github.com/Aohzan/ipx800v5/assets/104391247/75a58314-1a65-4d42-87b6-21e315371802)
![20230828_115809](https://github.com/Aohzan/ipx800v5/assets/104391247/52452948-ffad-4560-a3be-8ad3e6ca938a)
![20230828_115801](https://github.com/Aohzan/ipx800v5/assets/104391247/b57d7524-2b0f-47f6-ab2a-c779385e2422)
![20230828_115851](https://github.com/Aohzan/ipx800v5/assets/104391247/4bf4365e-b438-4d45-ae1c-11f9f49195fd)

**Comment by Aohzan** [comment]
hello
la configuration semble bonne en effet (tu peux copier ton code directement ici pour que ça soit plus lisible, pas besoin de le prendre en photo)
Est-ce que tu peux m'envoyer les logs en debug lors d'un reload stp ?
![image](https://github.com/Aohzan/ipx800v5/assets/2736322/4e2a69a3-db12-4c6d-9aa5-a96aa2e4a2e1)

**Comment by Mickaelclercq** [comment]
merci a vous pour votre réactivité, je suis désoler j'ai pas penser a vous envoyer le debug, je vous joint ceci en espérant que vous trouverez une solutions.
[home-assistant_ipx800v5_2023-08-28T12-33-40.712Z.log](https://github.com/Aohzan/ipx800v5/files/12454451/home-assistant_ipx800v5_2023-08-28T12-33-40.712Z.log)

**Comment by Aohzan** [comment]
tu peux essayer de supprimer l'intégration et de redémarrer Home-Assistant ?

**Comment by Mickaelclercq** [comment]
Voila désoler de revenir seulement maintenant vers toi, j'ai supprimer tout de l'intégration j'ai redémarrer home assistant puis j'ai tout installer mais cela ne fonctionne toujours pas j'ai juste ma sonde x-thl qui est bien configurée. Je te remet le log de mon dernier démarrage pour voir si tu comprend pourquoi cela ne fonctionne plus. Il n'y avait pas de manœuvres a réaliser avant de faire la mise a jour??? Merci a toi
[home-assistant_ipx800v5_2023-08-28T19-05-58.112Z.log](https://github.com/Aohzan/ipx800v5/files/12457507/home-assistant_ipx800v5_2023-08-28T19-05-58.112Z.log)

**Comment by Aohzan** [comment]
Tu as `The IPX800 V5 on 192.168.2.3 is already configured from the UI. Delete it first if you want to configure it from configuration.yaml` dans les logs
Tu as configuré depuis l'interface, il faut que tu supprimes l'intégration, et redémarrer Home-Assistant derrière
![image](https://github.com/Aohzan/ipx800v5/assets/2736322/4debaa37-02ca-426b-931d-bed45f33091b)
