### ISSUE TITLE
Lors du changement du polling plus aucune entité ne répond en YAML

### ISSUE THREAD

**Issue by mamatdv** [Aohzan/ipx800v5#14]
Lorsque je veux changer le temps de polling, plus aucune entité ne répond.

Seul solution, supprimer l'intégration dans l'ui et redémarré HA pour nouvelle prise en charge du YAML.

Pas d'erreurs dans les logs.

**Comment by Aohzan** [comment]
tu peux valider qu'en 1.6.3 c'est corrigé ?

**Comment by mamatdv** [comment]
Hello, Yes c'est tout bon maintenant. Merci
