### ISSUE TITLE
Problème d'autorisation, vérifiez la clé API

### ISSUE THREAD

**Issue by Alex123123123123123123123123** [Aohzan/ipx800v5#18]
Bonjour,

Lors de l'installation, connexion impossible avec le message "Problème d'autorisation, vérifiez la clé API"

<img width="567" alt="Capture d’écran 2024-09-23 à 21 48 22" src="https://github.com/user-attachments/assets/e8117563-3279-4cad-8f2a-c7a09752e238">

Auriez vous une idée ?

Bonne soirée

**Comment by Alex123123123123123123123123** [comment]
Non, j'aimerai bien ;)

**Comment by Aohzan** [comment]
Essaie de la changer côté IPX

**Comment by Alex123123123123123123123123** [comment]
Depuis la 1.8.2 ça fonctionne. Merci
