### ISSUE TITLE
X4VR: set position 0 not working

### ISSUE THREAD

**Issue by Floche** [Aohzan/ipx800v5#2]
Salut,

sur mes X4VR le set position 0 ne marche pas, mais set position de 1 à 100 oui.
N'hesite pas si tu as besoin de plus d'info.

Merci

**Comment by Aohzan** [comment]
Salut,
Peux-tu me dire les valeurs de l'analog de position quand :
- Volet fermé
- Volet ouvert
- Volet descendu de 20% (donc majoritaire ouvert)
Merci

**Comment by Floche** [comment]
Salut,
désolé je n'ai pas du tout eu le temps de m'y repencher. Je ne suis pas sur que l'erreur vienne de HA, c'est peut etre l'IPX car des fois ca marche et je n'arrive pas à mettre le doigt sur les changements.
Mes valeurs coté IPX sont normales, volet fermé 100, ouvert 0, ouvert à 80%: 20.

A+

**Comment by Aohzan** [comment]
Ok redis moi si tu notes quelque chose, normalement j'ai repris les mêmes paramètres que sur l'itnégration V4
