### ISSUE TITLE
Problème de réactivité appui X24-D

### ISSUE THREAD

**Issue by vinco81** [Aohzan/ipx800v5#22]
Bonjour, 
J'ai paramétré depuis quelques semaines le plugin IPX800 pour Home Assistant. Il fonctionne très bien. J'ai juste un problème lorsque je souhaite utiliser les entrée digitales de mes X24D pour générer des actions via Home Assistant. Il finit par capter l'action sur le bouton mais après l'avoir laissé appuyé pendant longtemps, et il y a un gros décalage entre l'appuis et l'action ce qui rend cette fonctionnalité inutilisable. Les actions sur les relais des X8-R sont immédiates et ne posent pas de soucis. 
Est ce que ce fonctionnement est normal ? Est ce que je peux faire quelque chose pour améliorer ce problème.

Merci par avance, 

Vincent

**Comment by Aohzan** [comment]
Bonjour,
Il faut configurer un push (voir README) pour que l'IPX envoie l'information à HA de façon instantannée.
Car en effet par défaut les informations sont récupérées tous les 10s environ
