### ISSUE TITLE
Bonjour,

### ISSUE THREAD

**Issue by cce66** [Aohzan/ipx800v5#3]
Petit souci pour l'accès à l'IPX800V5 si le port n'est pas le port 80 ! J'ai mis le mien à 50080 et...plus d'accès ! :-(

**Comment by Aohzan** [comment]
Tu as plus de détails ? C'est quand tu changes le port alors qu'il était en 80 ?

**Comment by cce66** [comment]
Bah en fait j'ai paramétré mon ipx800V5 sur le port 50080 pour ne pas le laisser sur le port 80 et ajouter dans le configuration.yaml car il n'y a pas de possibilité de le paramétrer dans le module, je débute sur HA et beau boulot cette intégration !
ipx800v5:
  - name: IPX800_V5-1
    host: 192.168.0.120
    port: 50080
    api_key: fHH0bhox2P8f5nn
    push_password: fHH0bhox2P8f5nn
    devices_auto:
      - ipx
      - x8r
      - x4vr
      - tempo
      - thermostat

**Comment by cce66** [comment]
Ok j'ai compris, en fait j'avais pas osé supprimer l'intégration et la réintégrer, en la réintégrant effectivement il est proposé de paramétrer l'IP le port et la key API, il faudrait pouvoir le paramétrer sans passer par cette étape mais bon une fois qu'on le sait !!! ;-)

**Comment by Aohzan** [comment]
Oui en effet c'est pas précisé mais c'est lié au fonctionnement de l'intégration et demanderait à changer pas mal de choses :)

ps: attention aux clés API et password en copiant la conf (j'ai caché)

**Comment by cce66** [comment]
Ah ok ! Bah faudrait juste l'ajouter dans le README.md ! On tout cas cela marches du feu de Dieu, du coup il m'a cherché mes X4VR tout seul, plus qu'a paramétrer dans l'UI (quoi c'est pas automatique !?  :-) ) Tu compte faire d'autre portage sur d'autre plateforme (Gladys par exmple) ?

**Comment by Aohzan** [comment]
Non ce n'est pas prévu, ça prend déjà beaucoup de temps à faire et maintenir :)

**Comment by cce66** [comment]
Dommmmmmmmmmage snniff mais effectivement cela doit être chronophage, j'espère que GCE te fais des remises !!! :-)
