### ISSUE TITLE
Intégration collecteur ouverts

### ISSUE THREAD

**Issue by lebrou34** [Aohzan/ipx800v5#6]
Hello 
Merci et super boulot sur cette intégration

Avec les 4 nouvelles sorties collecteurs ouvert disponible sur la v5, serait il possible de les rajouter sur l intégration ?

**Comment by Aohzan** [comment]
Hello,
merci :smiley: 
j'ai ajouté le support dans la dernière version si tu peux tester et valider

**Comment by lebrou34** [comment]
Merci pour ta réactivité ! Ça marche nickel now !!
