### ISSUE TITLE
Controler un telerupteur dans les objet

### ISSUE THREAD

**Issue by Mickaelclercq** [Aohzan/ipx800v5#9]
Bonjour je me permets de venir vers vous car je cherche à contrôler directement un telerupteur qui se situe dans les objet  de l'ipx 800 v5 je met en photo les description. Est-ce que dans le yaml je dois l'indique comme les io et en id mettre le nom??

name: Mon telerupteur
        component: switch
        ext_type: ipx
        type: io
        id: chambre parents
Merci d'avance. Bonne journée.

![Screenshot_20221209_192013_Chrome](https://user-images.githubusercontent.com/104391247/206791686-b33e02ad-a223-40b1-ac29-32283ec74c02.jpg)
![Screenshot_20221209_192017_Chrome](https://user-images.githubusercontent.com/104391247/206791708-aa400ed4-71eb-47b9-a5f3-582d66ad3d55.jpg)

**Comment by Aohzan** [comment]
bonjour, en id il faut indiquer un nombre, vous le trouverez en passant le curseur sur le cercle de l'entrée, exemple 
![image](https://user-images.githubusercontent.com/2736322/206794278-c53743b6-ca54-46de-b7de-48b82acda8a0.png)
